services:
  jenkins:
    build: .  # Utilise le Dockerfile dans le répertoire courant
    user: root  # Important pour accéder au socket Docker
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Montage du socket Docker
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true

volumes:
  jenkins_home:
